In [1]:
import pandas as pd 
df=pd.read_csv("/kaggle/input/genotype-data-csv/Genotypic_Data.csv") 
df

,SNPs,alleles,Chrom,Pos,strand,assembly,center,protLSID,assayLSID,panel,...,HD3372,HI1655,AKAW5088,MACS6753,DBW330,DBW173,DBW187,MACS6222,WH1124,WH1142
0,AX-94381285,C/T,1A,65900002,+,NaN,NaN,NaN,NaN,wheat,...,CC,NaN,CC,CC,TC,CC,CC,TC,CC,TC
1,AX-94383718,A/G,1A,49998880,+,NaN,NaN,NaN,NaN,wheat,...,AA,AA,AA,AA,AG,AA,AA,AG,AA,AG
2,AX-94384181,A/G,1A,482328679,+,NaN,NaN,NaN,NaN,wheat,...,AA,GG,AA,AA,GG,GG,AA,AA,GG,GG
3,AX-94384966,T/C,1A,588302549,+,NaN,NaN,NaN,NaN,wheat,...,TT,TT,CC,TT,CC,TT,TT,TT,TT,CC
4,AX-94386458,C/A,1A,3392719,+,NaN,NaN,NaN,NaN,wheat,...,AA,CC,CC,CC,CC,CC,CC,CC,CC,CC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,AX-95255434,C/T,7D,27651969,+,NaN,NaN,NaN,NaN,wheat,...,TC,NaN,CC,TC,TC,TC,CC,NaN,CC,TT
14786,AX-95257606,A/G,7D,528134787,+,NaN,NaN,NaN,NaN,wheat,...,AA,GG,AA,AA,AA,AA,AA,AA,AA,AA
14787,AX-95258647,G/T,7D,7072875,+,NaN,NaN,NaN,NaN,wheat,...,GG,GG,GG,GG,TT,GG,TT,GG,GG,GG
14788,AX-95258998,G/T,7D,626145852,+,NaN,NaN,NaN,NaN,wheat,...,GG,GG,GG,GG,GG,TG,NaN,GG,TT,GG
14789,AX-95259412,T/C,7D,8560670,+,NaN,NaN,NaN,NaN,wheat,...,CC,TT,CC,TT,TT,TT,TT,TT,CC,TT

In [2]:
def replace_none_with_first_char(row, column_name):
    if pd.isna(row[column_name]):
        return row['alleles'][2]
    else:
        return row[column_name]

# List of columns to process
columns_to_process = df.columns

# Apply the function to each specified column in the DataFrame
for column in columns_to_process:
    df[column] = df.apply(replace_none_with_first_char, axis=1, column_name=column)

# Display the updated DataFrame
rep={'AA': 1, 'AC': 2, 'AG': 3,'AT': 4, 'CC': 5, 'CG': 6,'TC': 7, 'TG': 8, 'TT': 9,'GG':10, 'A':11, 'C':12, 'G':13, 'T':14}
df=df.replace(rep)
df

,SNPs,alleles,Chrom,Pos,strand,assembly,center,protLSID,assayLSID,panel,...,HD3372,HI1655,AKAW5088,MACS6753,DBW330,DBW173,DBW187,MACS6222,WH1124,WH1142
0,AX-94381285,C/T,1A,65900002,+,14,14,14,14,wheat,...,5,14,5,5,7,5,5,7,5,7
1,AX-94383718,A/G,1A,49998880,+,13,13,13,13,wheat,...,1,1,1,1,3,1,1,3,1,3
2,AX-94384181,A/G,1A,482328679,+,13,13,13,13,wheat,...,1,10,1,1,10,10,1,1,10,10
3,AX-94384966,T/C,1A,588302549,+,12,12,12,12,wheat,...,9,9,5,9,5,9,9,9,9,5
4,AX-94386458,C/A,1A,3392719,+,11,11,11,11,wheat,...,1,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,AX-95255434,C/T,7D,27651969,+,14,14,14,14,wheat,...,7,14,5,7,7,7,5,14,5,9
14786,AX-95257606,A/G,7D,528134787,+,13,13,13,13,wheat,...,1,10,1,1,1,1,1,1,1,1
14787,AX-95258647,G/T,7D,7072875,+,14,14,14,14,wheat,...,10,10,10,10,9,10,9,10,10,10
14788,AX-95258998,G/T,7D,626145852,+,14,14,14,14,wheat,...,10,10,10,10,10,8,14,10,9,10
14789,AX-95259412,T/C,7D,8560670,+,12,12,12,12,wheat,...,5,9,5,9,9,9,9,9,5,9

In [3]:
columns_to_drop = ['SNPs','alleles','Chrom','Pos','strand','assembly','center','protLSID','assayLSID','panel','QCcode']
df1= df.drop(columns=columns_to_drop)

In [4]:
df_transposed = df1.T
df_transposed.reset_index(inplace=True)
df_transposed.rename(columns={'index': 'Genotype'}, inplace=True)

df_transposed

,Genotype,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
0,AAI-W29,5,1,13,9,1,3,5,1,1,...,13,9,10,5,8,5,1,14,10,5
1,AKAW5080,5,1,13,5,2,3,5,1,1,...,1,9,10,5,9,9,1,9,10,9
2,AKAW5099,5,1,1,9,5,1,9,10,1,...,10,9,10,5,9,5,1,9,8,5
3,BRW3877,5,1,3,7,5,1,12,1,13,...,3,9,10,5,8,5,1,10,9,5
4,CG1029,14,1,10,9,2,1,9,1,3,...,13,9,10,5,9,5,1,9,10,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,DBW173,5,1,10,9,5,1,5,10,1,...,1,9,10,5,9,7,1,10,8,9
276,DBW187,5,1,1,9,5,1,9,10,1,...,1,9,10,5,9,5,1,9,14,9
277,MACS6222,7,3,1,9,5,1,9,1,1,...,1,9,10,5,9,14,1,10,10,9
278,WH1124,5,1,10,9,5,1,5,1,1,...,1,9,10,5,9,5,1,10,9,5
279,WH1142,7,3,10,5,5,1,5,10,1,...,1,9,10,5,9,9,1,10,10,9

In [5]:
import pandas as pd

# Load your data from the CSV file
df2 = pd.read_csv('/kaggle/input/phenotypic-data/phenotypic_Data.csv')

df2

,Genotype,DH_Dharwad,DH_IARI-DELHI,DH_IARI-Jharkhand,DH_KARNAL,DH_Pooled,GFD_Dharwad,GFD_IARI-Delhi,GFD_IARI-Jharkhand,GFD_Karnal,...,PH_IARI-Jharkhand,PH_Karnal,PH_Ludhiana,PH_Pooled,GY_Dharwad,GY_IARI-Delhi,GY_IARI-JKD,GY_Karnal,GY_Ludhiana,GY_Pooled
0,AAI-W22,62.843,97.468,88.419,98.679,86.794,44.283,44.827,31.243,40.735,...,91.142,104.939,103.318,89.721,185.590,319.822,205.130,500.739,414.035,314.458
1,AAI-W29,60.066,105.083,87.388,95.276,87.275,44.283,44.827,32.920,42.738,...,105.472,118.113,109.544,105.657,340.663,387.690,239.604,506.012,426.714,377.428
2,AKAW5080,55.096,96.634,79.600,89.991,80.225,44.283,44.827,37.318,45.636,...,94.379,109.194,107.107,98.548,238.635,376.340,246.852,479.973,580.827,381.368
3,AKAW5088,54.560,89.019,84.524,88.990,78.530,44.283,44.827,31.792,47.256,...,100.650,112.074,117.128,104.708,256.817,419.135,255.861,555.774,487.549,392.886
4,AKAW5099,54.268,85.369,81.547,86.468,76.579,44.283,44.827,29.071,47.809,...,93.587,103.843,99.796,93.936,369.539,392.419,256.515,551.579,527.685,423.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,WH1279,63.671,101.223,89.392,96.037,87.524,44.283,44.827,31.243,41.460,...,94.312,110.290,109.004,97.983,321.307,485.343,279.213,582.404,546.891,445.046
276,WH1280,60.358,97.468,89.392,96.037,85.579,44.283,44.827,32.342,41.460,...,99.858,110.290,100.881,94.141,260.667,404.947,251.835,564.651,522.977,400.203
277,WH1281,62.014,101.223,93.286,102.203,89.711,44.283,44.827,31.243,37.113,...,100.650,121.884,109.004,105.669,444.510,513.718,263.913,552.815,592.948,471.501
278,WH1283,59.530,92.774,85.498,95.156,82.905,44.283,44.827,28.493,42.184,...,106.989,106.723,108.192,99.136,291.468,537.364,265.524,611.994,572.577,461.181
279,WH1284,58.701,89.958,84.524,91.633,80.717,44.283,44.827,30.143,45.082,...,104.612,117.425,110.629,103.363,594.665,537.364,266.329,614.361,573.463,521.409

In [6]:
DH_Pooled=df2[['Genotype', 'DH_Pooled']]
GFD_Pooled=df2[['Genotype', 'GFD_Pooled']]
GNPS_Pooled=df2[['Genotype', 'GNPS_Pooled']]
GWPS_Pooled=df2[['Genotype', 'GWPS_Pooled']]
PH_Pooled=df2[['Genotype','PH_Pooled']]
GY_Pooled=df2[['Genotype', 'GY_Pooled']]
GY_Pooled

     Genotype  GY_Pooled
0     AAI-W22    314.458
1     AAI-W29    377.428
2    AKAW5080    381.368
3    AKAW5088    392.886
4    AKAW5099    423.772
..        ...        ...
275    WH1279    445.046
276    WH1280    400.203
277    WH1281    471.501
278    WH1283    461.181
279    WH1284    521.409

[280 rows x 2 columns]

In [7]:
merged_df = pd.merge(DH_Pooled,df_transposed, on='Genotype')

# Display the merged DataFrame
print("Merged DataFrame:")
merged_df

Merged DataFrame:

,Genotype,DH_Pooled,0,1,2,3,4,5,6,7,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
0,AAI-W22,86.794,7,1,1,5,5,1,9,1,...,1,9,10,5,9,14,10,10,10,5
1,AAI-W29,87.275,5,1,13,9,1,3,5,1,...,13,9,10,5,8,5,1,14,10,5
2,AKAW5080,80.225,5,1,13,5,2,3,5,1,...,1,9,10,5,9,9,1,9,10,9
3,AKAW5088,78.530,5,1,1,5,5,1,9,10,...,1,9,10,5,9,5,1,10,10,5
4,AKAW5099,76.579,5,1,1,9,5,1,9,10,...,10,9,10,5,9,5,1,9,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,WH1279,87.524,5,1,10,9,5,13,5,1,...,10,9,10,5,9,5,1,9,10,9
276,WH1280,85.579,5,1,10,9,1,1,5,1,...,1,5,6,5,9,5,10,8,14,9
277,WH1281,89.711,5,1,1,12,11,3,9,10,...,1,9,10,5,8,7,1,10,8,9
278,WH1283,82.905,14,1,10,5,5,1,5,10,...,10,9,10,5,9,9,1,10,14,5
279,WH1284,80.717,5,1,1,5,11,13,9,10,...,10,9,10,7,8,7,1,10,14,9

In [8]:
merged_df.drop('Genotype', axis=1, inplace=True)

In [9]:
correlation_matrix = merged_df.corr()
correlation_matrix

,DH_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
DH_Pooled,1.000000,0.035386,0.022106,0.065751,0.054070,-0.077251,0.054374,-0.061731,-0.040366,-0.067536,...,-0.024850,-0.050910,0.004609,0.005216,0.040276,-0.079391,0.086755,-0.030450,-0.010364,0.053858
0,0.035386,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,0.022106,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,0.065751,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,0.054070,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,-0.079391,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,0.086755,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,-0.030450,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,-0.010364,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,0.053858,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [10]:
import pandas as pd

# Assuming 'GFD_Pooled' is the column for which you want correlation values
column_name = 'DH_Pooled'
corr_DH= correlation_matrix[column_name]
sel_DH= corr_DH[corr_DH > 0.035]

# Set the index name as 'index'
sel_DH.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
sel_DH

Selected DataFrame:

index
DH_Pooled    1.000000
0            0.035386
2            0.065751
3            0.054070
5            0.054374
               ...
14767        0.064836
14778        0.052516
14784        0.040276
14786        0.086755
14789        0.053858
Name: DH_Pooled, Length: 5036, dtype: float64

In [11]:
merged_df = pd.merge(GFD_Pooled,df_transposed, on='Genotype')
merged_df.drop('Genotype', axis=1, inplace=True)

In [12]:
correlation_matrix_gfd= merged_df.corr()
correlation_matrix_gfd

,GFD_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
GFD_Pooled,1.000000,-0.040267,-0.068192,-0.030393,-0.021146,0.048193,-0.122495,0.069997,0.001236,0.026710,...,-0.051642,0.058383,0.027726,-0.055084,-0.112860,-0.061256,-0.074718,0.038844,-0.008810,-0.073726
0,-0.040267,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,-0.068192,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,-0.030393,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,-0.021146,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,-0.061256,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,-0.074718,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,0.038844,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,-0.008810,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,-0.073726,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [13]:
import pandas as pd

# Assuming 'GFD_Pooled' is the column for which you want correlation values
column_name = 'GFD_Pooled'
corr_GFD = correlation_matrix_gfd[column_name]
sel_GFD = corr_GFD[corr_GFD > 0.035]


# Set the index name as 'index'
sel_GFD.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
print(sel_GFD)

Selected DataFrame:
index
GFD_Pooled    1.000000
4             0.048193
6             0.069997
12            0.063911
15            0.043249
                ...
14775         0.208459
14776         0.042065
14777         0.060531
14781         0.058383
14787         0.038844
Name: GFD_Pooled, Length: 5139, dtype: float64

In [14]:
merged_df = pd.merge(GNPS_Pooled,df_transposed, on='Genotype')
merged_df.drop('Genotype', axis=1, inplace=True)

In [15]:
correlation_matrix_gnps= merged_df.corr()
correlation_matrix_gnps

,GNPS_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
GNPS_Pooled,1.000000,0.079587,0.031369,-0.055315,-0.100825,0.012683,-0.030315,0.067581,0.128044,0.017914,...,0.052348,0.030647,0.027098,-0.034139,0.037987,0.145302,0.050374,0.046935,0.082861,0.101513
0,0.079587,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,0.031369,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,-0.055315,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,-0.100825,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,0.145302,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,0.050374,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,0.046935,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,0.082861,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,0.101513,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [16]:
import pandas as pd
column_name = 'GNPS_Pooled'
corr_GNPS= correlation_matrix_gnps[column_name]
sel_GNPS=corr_GNPS[corr_GNPS > 0.035]


# Set the index name as 'index'
sel_GNPS.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
print(sel_GNPS)

Selected DataFrame:
index
GNPS_Pooled    1.000000
0              0.079587
6              0.067581
7              0.128044
10             0.112793
                 ...
14785          0.145302
14786          0.050374
14787          0.046935
14788          0.082861
14789          0.101513
Name: GNPS_Pooled, Length: 4943, dtype: float64

In [17]:
merged_df = pd.merge(GWPS_Pooled,df_transposed, on='Genotype')
merged_df.drop('Genotype', axis=1, inplace=True)

In [18]:
correlation_matrix_gwps= merged_df.corr()
correlation_matrix_gwps

,GWPS_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
GWPS_Pooled,1.000000,-0.026984,-0.015249,-0.186738,-0.013676,0.069261,0.006733,0.161589,0.113595,0.039124,...,0.070793,0.092714,-0.002914,-0.036598,0.036165,0.067825,0.009813,0.040719,-0.029477,0.106754
0,-0.026984,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,-0.015249,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,-0.186738,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,-0.013676,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,0.067825,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,0.009813,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,0.040719,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,-0.029477,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,0.106754,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [19]:
import pandas as pd
column_name = 'GWPS_Pooled'
corr_GWPS= correlation_matrix_gwps[column_name]
sel_GWPS=corr_GWPS[corr_GWPS>0.035]


# Set the index name as 'index'
sel_GWPS.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
print(sel_GWPS)

Selected DataFrame:
index
GWPS_Pooled    1.000000
4              0.069261
6              0.161589
7              0.113595
8              0.039124
                 ...
14781          0.092714
14784          0.036165
14785          0.067825
14787          0.040719
14789          0.106754
Name: GWPS_Pooled, Length: 5064, dtype: float64

In [20]:
merged_df = pd.merge(PH_Pooled,df_transposed, on='Genotype')
merged_df.drop('Genotype', axis=1, inplace=True)

In [21]:
correlation_matrix_ph= merged_df.corr()
correlation_matrix_ph

,PH_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
PH_Pooled,1.000000,0.000964,-0.121679,-0.029803,-0.041628,-0.123958,0.000087,-0.041623,0.035254,-0.094976,...,0.040976,0.000218,-0.070405,-0.007564,0.037936,0.098694,-0.003651,0.007664,0.050751,0.161421
0,0.000964,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,-0.121679,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,-0.029803,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,-0.041628,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,0.098694,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,-0.003651,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,0.007664,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,0.050751,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,0.161421,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [22]:
import pandas as pd
column_name = 'PH_Pooled'
corr_PH= correlation_matrix_ph[column_name]
sel_PH=corr_PH[corr_PH>0.035]


# Set the index name as 'index'
sel_PH.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
print(sel_PH)

Selected DataFrame:
index
PH_Pooled    1.000000
7            0.035254
10           0.083875
13           0.048297
16           0.069400
               ...
14780        0.040976
14784        0.037936
14785        0.098694
14788        0.050751
14789        0.161421
Name: PH_Pooled, Length: 4446, dtype: float64

In [23]:
merged_df = pd.merge(GY_Pooled,df_transposed, on='Genotype')
merged_df.drop('Genotype', axis=1, inplace=True)

In [24]:
correlation_matrix_gy= merged_df.corr()
correlation_matrix_gy

,GY_Pooled,0,1,2,3,4,5,6,7,8,...,14780,14781,14782,14783,14784,14785,14786,14787,14788,14789
GY_Pooled,1.000000,0.003837,-0.058944,-0.088322,-0.004733,0.017196,0.085738,0.071655,0.119755,0.030744,...,0.087233,0.002260,0.035780,0.037979,0.104038,-0.019590,-0.084491,-0.036235,0.004383,0.120680
0,0.003837,1.000000,0.227183,0.102238,-0.068386,-0.094309,-0.071021,-0.056807,-0.055828,-0.045870,...,0.003176,0.061515,-0.044055,-0.053172,0.016943,0.171512,0.121623,0.118466,0.013520,-0.010316
1,-0.058944,0.227183,1.000000,0.056575,0.012995,-0.106892,-0.075926,-0.037923,0.035796,0.026366,...,0.088077,0.007492,-0.000414,0.035749,-0.101008,0.021343,0.150162,0.052360,-0.080785,0.007454
2,-0.088322,0.102238,0.056575,1.000000,-0.009217,-0.017070,-0.123260,-0.644653,-0.146708,0.010855,...,-0.103596,-0.079300,-0.015811,-0.224227,-0.069866,-0.059883,0.069165,-0.114500,-0.000715,-0.076304
3,-0.004733,-0.068386,0.012995,-0.009217,1.000000,0.025087,0.045525,-0.015157,-0.094817,0.101977,...,-0.042947,0.008577,-0.024663,-0.028481,0.042873,-0.146048,0.013128,-0.120669,0.065926,0.118469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,-0.019590,0.171512,0.021343,-0.059883,-0.146048,-0.064335,-0.046178,0.074348,0.077431,-0.040075,...,0.020917,0.122159,0.004849,-0.058466,0.013678,1.000000,0.023041,0.024812,0.074385,0.199146
14786,-0.084491,0.121623,0.150162,0.069165,0.013128,-0.145603,0.052433,-0.036086,-0.077046,0.111717,...,0.077515,-0.151345,-0.644237,-0.045033,-0.033284,0.023041,1.000000,-0.028181,0.075773,-0.084888
14787,-0.036235,0.118466,0.052360,-0.114500,-0.120669,-0.032025,-0.047693,0.051046,0.042006,-0.045480,...,0.064875,-0.024387,0.020323,-0.008116,0.014336,0.024812,-0.028181,1.000000,0.030687,-0.128613
14788,0.004383,0.013520,-0.080785,-0.000715,0.065926,-0.049108,0.054246,0.037041,0.007901,-0.044966,...,0.012604,-0.057723,-0.059823,0.005350,0.038206,0.074385,0.075773,0.030687,1.000000,0.090654
14789,0.120680,-0.010316,0.007454,-0.076304,0.118469,0.062492,0.049713,0.045618,0.136596,-0.019803,...,0.041242,-0.007142,0.051737,0.132291,0.031631,0.199146,-0.084888,-0.128613,0.090654,1.000000

In [25]:
import pandas as pd
column_name = 'GY_Pooled'
corr_GY= correlation_matrix_gy[column_name]
sel_GY=corr_GY[corr_GY>0.035]

# Set the index name as 'index'
sel_GY.index.name = 'index'

# Display the DataFrame with selected columns and the new column names
print("Selected DataFrame:")
print(sel_GY)

Selected DataFrame:
index
GY_Pooled    1.000000
5            0.085738
6            0.071655
7            0.119755
10           0.121192
               ...
14780        0.087233
14782        0.035780
14783        0.037979
14784        0.104038
14789        0.120680
Name: GY_Pooled, Length: 5011, dtype: float64

In [26]:
dfs = [sel_DH,sel_GFD,sel_GNPS, sel_GWPS,sel_GY,sel_PH]

# Extract indices for each dataframe
index_sets = [set(df.index) for df in dfs]

# # Display individual indices for each Series
# for i, indices in enumerate(index_sets, 1):
#     print(f"Indices for Series {i}: {indices}")

# Find the common indices (rows)
common_rows = set.intersection(*index_sets)

# Display the common rows
print("\nCommon Rows:")
print(len(common_rows))

Common Rows:
8

In [27]:
import pandas as pd

# Assuming dfs is a list of your DataFrames (sel_DH, sel_GFD, sel_GNPS, sel_GWPS, sel_GY, sel_PH)
dfs = [sel_DH, sel_GFD, sel_GNPS, sel_GWPS, sel_GY, sel_PH]

# Merge DataFrames on their indices using reduce
from functools import reduce
common_rows_data = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True), dfs)

# Display the data for common rows from the merged DataFrame
print("Data for Common Rows in the Merged DataFrame:")
print(common_rows_data.shape)
common_rows_data

Data for Common Rows in the Merged DataFrame:
(8, 6)

       DH_Pooled  GFD_Pooled  GNPS_Pooled  GWPS_Pooled  GY_Pooled  PH_Pooled
index
869     0.037969    0.054146     0.049703     0.037737   0.052752   0.045630
3089    0.045200    0.043561     0.075194     0.060276   0.144296   0.041026
5700    0.065088    0.040976     0.047703     0.089144   0.128806   0.098035
6227    0.061528    0.046207     0.086539     0.084102   0.097760   0.035818
6286    0.037447    0.087170     0.089165     0.111635   0.050986   0.107021
7750    0.041088    0.051274     0.056996     0.061520   0.041096   0.042098
8288    0.035747    0.036224     0.140418     0.132475   0.117126   0.039599
14204   0.036663    0.035920     0.107332     0.051013   0.051453   0.066581

In [28]:
df=pd.read_csv("/kaggle/input/genotype-data-csv/Genotypic_Data.csv")
df

,SNPs,alleles,Chrom,Pos,strand,assembly,center,protLSID,assayLSID,panel,...,HD3372,HI1655,AKAW5088,MACS6753,DBW330,DBW173,DBW187,MACS6222,WH1124,WH1142
0,AX-94381285,C/T,1A,65900002,+,NaN,NaN,NaN,NaN,wheat,...,CC,NaN,CC,CC,TC,CC,CC,TC,CC,TC
1,AX-94383718,A/G,1A,49998880,+,NaN,NaN,NaN,NaN,wheat,...,AA,AA,AA,AA,AG,AA,AA,AG,AA,AG
2,AX-94384181,A/G,1A,482328679,+,NaN,NaN,NaN,NaN,wheat,...,AA,GG,AA,AA,GG,GG,AA,AA,GG,GG
3,AX-94384966,T/C,1A,588302549,+,NaN,NaN,NaN,NaN,wheat,...,TT,TT,CC,TT,CC,TT,TT,TT,TT,CC
4,AX-94386458,C/A,1A,3392719,+,NaN,NaN,NaN,NaN,wheat,...,AA,CC,CC,CC,CC,CC,CC,CC,CC,CC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,AX-95255434,C/T,7D,27651969,+,NaN,NaN,NaN,NaN,wheat,...,TC,NaN,CC,TC,TC,TC,CC,NaN,CC,TT
14786,AX-95257606,A/G,7D,528134787,+,NaN,NaN,NaN,NaN,wheat,...,AA,GG,AA,AA,AA,AA,AA,AA,AA,AA
14787,AX-95258647,G/T,7D,7072875,+,NaN,NaN,NaN,NaN,wheat,...,GG,GG,GG,GG,TT,GG,TT,GG,GG,GG
14788,AX-95258998,G/T,7D,626145852,+,NaN,NaN,NaN,NaN,wheat,...,GG,GG,GG,GG,GG,TG,NaN,GG,TT,GG
14789,AX-95259412,T/C,7D,8560670,+,NaN,NaN,NaN,NaN,wheat,...,CC,TT,CC,TT,TT,TT,TT,TT,CC,TT

In [29]:
def replace_none_with_first_char(row, column_name):
    if pd.isna(row[column_name]):
        return row['alleles'][2]
    else:
        return row[column_name]

# List of columns to process
columns_to_process = df.columns

# Apply the function to each specified column in the DataFrame
for column in columns_to_process:
    df[column] = df.apply(replace_none_with_first_char, axis=1, column_name=column)

In [30]:
selected_rows_indices = [869,3089,5700,6227,6286,7750,8288,14204]

# Using iloc to extract specific rows
df_selected_rows= df.iloc[selected_rows_indices]

# Using loc to extract specific rows
df_selected_rows_loc = df.loc[selected_rows_indices]

# Display the original DataFrame and the new DataFrames with selected rows

print("\nDataFrame with Selected Rows using iloc:")
df_selected_rows

DataFrame with Selected Rows using iloc:

,SNPs,alleles,Chrom,Pos,strand,assembly,center,protLSID,assayLSID,panel,...,HD3372,HI1655,AKAW5088,MACS6753,DBW330,DBW173,DBW187,MACS6222,WH1124,WH1142
869,AX-94462858,G/A,1B,553146272,+,A,A,A,A,wheat,...,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG
3089,AX-94633131,T/G,2A,45123164,+,G,G,G,G,wheat,...,TT,TT,TT,TT,TT,TT,TT,TT,TT,G
5700,AX-94578679,G/T,3A,61446196,+,T,T,T,T,wheat,...,GG,GG,TT,GG,GG,GG,GG,GG,GG,GG
6227,AX-94480569,G/A,3B,478555437,+,A,A,A,A,wheat,...,AG,AA,AG,AA,GG,GG,GG,AA,GG,GG
6286,AX-94524677,T/A,3B,514593813,+,A,A,A,A,wheat,...,TT,AA,AT,TT,TT,TT,TT,AA,AA,TT
7750,AX-94794039,C/T,4A,602797769,+,T,T,T,T,wheat,...,TT,TT,TT,TT,TT,TT,TT,CC,CC,CC
8288,AX-94987158,G/T,4B,167346674,+,T,T,T,T,wheat,...,GG,GG,GG,GG,GG,GG,GG,GG,GG,GG
14204,AX-94424480,T/C,7D,38184107,+,C,C,C,C,wheat,...,TT,TT,TT,CC,TT,TT,C,TT,TT,CC

In [31]:
columns_to_drop = ['SNPs','alleles','Chrom','Pos','strand','assembly','center','protLSID','assayLSID','panel','QCcode']
df1= df_selected_rows.drop(columns=columns_to_drop)

In [32]:
df_transposed= df1.T
df_transposed.reset_index(inplace=True)
df_transposed.rename(columns={'index': 'Genotype'}, inplace=True)

df_transposed

     Genotype 869 3089 5700 6227 6286 7750 8288 14204
0     AAI-W29  GG   TG    T   GG   TT   TC   GG    TT
1    AKAW5080  GG   TT   GG   GG   TT   CC   GG    CC
2    AKAW5099  GG    G   TT   GG   AA   CC   GG    CC
3     BRW3877  GG    G   GG   AA   AA   CC   GG     C
4      CG1029  GG   TG   TT   GG   TT   TT   TT    CC
..        ...  ..  ...  ...  ...  ...  ...  ...   ...
275    DBW173  GG   TT   GG   GG   TT   TT   GG    TT
276    DBW187  GG   TT   GG   GG   TT   TT   GG     C
277  MACS6222  GG   TT   GG   AA   AA   CC   GG    TT
278    WH1124  GG   TT   GG   GG   AA   CC   GG    TT
279    WH1142  GG    G   GG   GG   TT   CC   GG    CC

[280 rows x 9 columns]

In [33]:
DH_Pooled=df2[['Genotype', 'DH_Pooled']]
GFD_Pooled=df2[['Genotype', 'GFD_Pooled']]
GNPS_Pooled=df2[['Genotype', 'GNPS_Pooled']]
GWPS_Pooled=df2[['Genotype', 'GWPS_Pooled']]
PH_Pooled=df2[['Genotype','PH_Pooled']]
GY_Pooled=df2[['Genotype', 'GY_Pooled']]
GY_Pooled

     Genotype  GY_Pooled
0     AAI-W22    314.458
1     AAI-W29    377.428
2    AKAW5080    381.368
3    AKAW5088    392.886
4    AKAW5099    423.772
..        ...        ...
275    WH1279    445.046
276    WH1280    400.203
277    WH1281    471.501
278    WH1283    461.181
279    WH1284    521.409

[280 rows x 2 columns]

In [34]:
merged_DH = pd.merge(df_transposed,DH_Pooled, on='Genotype')
merged_GFD = pd.merge(merged_DH,GFD_Pooled, on='Genotype')
merged_GNPS = pd.merge(merged_GFD,GNPS_Pooled, on='Genotype')
merged_GWPS = pd.merge(merged_GNPS,GWPS_Pooled,  on='Genotype')
merged_PH = pd.merge(merged_GWPS,PH_Pooled, on='Genotype')
merged_GY = pd.merge(merged_PH,GY_Pooled,on='Genotype')

merged_GY.to_csv("/kaggle/working/final_table1")
merged_GY

,Genotype,869,3089,5700,6227,6286,7750,8288,14204,DH_Pooled,GFD_Pooled,GNPS_Pooled,GWPS_Pooled,PH_Pooled,GY_Pooled
0,AAI-W29,GG,TG,T,GG,TT,TC,GG,TT,87.275,43.136,54.635,2.487,105.657,377.428
1,AKAW5080,GG,TT,GG,GG,TT,CC,GG,CC,80.225,44.570,47.878,1.955,98.548,381.368
2,AKAW5099,GG,G,TT,GG,AA,CC,GG,CC,76.579,45.286,56.952,2.559,93.936,423.772
3,BRW3877,GG,G,GG,AA,AA,CC,GG,C,84.358,42.897,53.187,2.200,103.351,461.672
4,CG1029,GG,TG,TT,GG,TT,TT,TT,CC,81.684,45.047,35.377,2.167,92.207,424.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,DBW173,GG,TT,GG,GG,TT,TT,GG,TT,86.794,42.420,59.437,2.398,100.673,478.818
276,DBW187,GG,TT,GG,GG,TT,TT,GG,C,82.464,44.362,45.776,2.475,98.719,461.657
277,MACS6222,GG,TT,GG,AA,AA,CC,GG,TT,90.442,40.267,54.487,2.405,95.316,437.051
278,WH1124,GG,TT,GG,GG,AA,CC,GG,TT,81.540,43.646,45.875,2.095,94.597,409.141
279,WH1142,GG,G,GG,GG,TT,CC,GG,CC,85.052,43.236,59.132,2.377,100.061,418.770

In [35]:
new=pd.merge(df_transposed,GNPS_Pooled, on='Genotype')
new1=pd.merge(new,GWPS_Pooled, on='Genotype')
new1.to_csv("/kaggle/working/final_table2")
new1

,Genotype,869,3089,5700,6227,6286,7750,8288,14204,GNPS_Pooled,GWPS_Pooled
0,AAI-W29,GG,TG,T,GG,TT,TC,GG,TT,54.635,2.487
1,AKAW5080,GG,TT,GG,GG,TT,CC,GG,CC,47.878,1.955
2,AKAW5099,GG,G,TT,GG,AA,CC,GG,CC,56.952,2.559
3,BRW3877,GG,G,GG,AA,AA,CC,GG,C,53.187,2.200
4,CG1029,GG,TG,TT,GG,TT,TT,TT,CC,35.377,2.167
...,...,...,...,...,...,...,...,...,...,...,...
275,DBW173,GG,TT,GG,GG,TT,TT,GG,TT,59.437,2.398
276,DBW187,GG,TT,GG,GG,TT,TT,GG,C,45.776,2.475
277,MACS6222,GG,TT,GG,AA,AA,CC,GG,TT,54.487,2.405
278,WH1124,GG,TT,GG,GG,AA,CC,GG,TT,45.875,2.095
279,WH1142,GG,G,GG,GG,TT,CC,GG,CC,59.132,2.377

In [36]:
new=pd.merge(df_transposed,GWPS_Pooled, on='Genotype')
new2=pd.merge(new,GY_Pooled, on='Genotype')
new2.to_csv("/kaggle/working/final_table3")
new2

     Genotype 869 3089 5700 6227 6286 7750 8288 14204  GWPS_Pooled  GY_Pooled
0     AAI-W29  GG   TG    T   GG   TT   TC   GG    TT        2.487    377.428
1    AKAW5080  GG   TT   GG   GG   TT   CC   GG    CC        1.955    381.368
2    AKAW5099  GG    G   TT   GG   AA   CC   GG    CC        2.559    423.772
3     BRW3877  GG    G   GG   AA   AA   CC   GG     C        2.200    461.672
4      CG1029  GG   TG   TT   GG   TT   TT   TT    CC        2.167    424.710
..        ...  ..  ...  ...  ...  ...  ...  ...   ...          ...        ...
275    DBW173  GG   TT   GG   GG   TT   TT   GG    TT        2.398    478.818
276    DBW187  GG   TT   GG   GG   TT   TT   GG     C        2.475    461.657
277  MACS6222  GG   TT   GG   AA   AA   CC   GG    TT        2.405    437.051
278    WH1124  GG   TT   GG   GG   AA   CC   GG    TT        2.095    409.141
279    WH1142  GG    G   GG   GG   TT   CC   GG    CC        2.377    418.770

[280 rows x 11 columns]

In [37]:
new=pd.merge(df_transposed,GNPS_Pooled, on='Genotype')
new3=pd.merge(new,GY_Pooled, on='Genotype')
new3.to_csv("/kaggle/working/final_table4")
new3

     Genotype 869 3089 5700 6227 6286 7750 8288 14204  GNPS_Pooled  GY_Pooled
0     AAI-W29  GG   TG    T   GG   TT   TC   GG    TT       54.635    377.428
1    AKAW5080  GG   TT   GG   GG   TT   CC   GG    CC       47.878    381.368
2    AKAW5099  GG    G   TT   GG   AA   CC   GG    CC       56.952    423.772
3     BRW3877  GG    G   GG   AA   AA   CC   GG     C       53.187    461.672
4      CG1029  GG   TG   TT   GG   TT   TT   TT    CC       35.377    424.710
..        ...  ..  ...  ...  ...  ...  ...  ...   ...          ...        ...
275    DBW173  GG   TT   GG   GG   TT   TT   GG    TT       59.437    478.818
276    DBW187  GG   TT   GG   GG   TT   TT   GG     C       45.776    461.657
277  MACS6222  GG   TT   GG   AA   AA   CC   GG    TT       54.487    437.051
278    WH1124  GG   TT   GG   GG   AA   CC   GG    TT       45.875    409.141
279    WH1142  GG    G   GG   GG   TT   CC   GG    CC       59.132    418.770

[280 rows x 11 columns]